/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import exceptions.WrongNumberException;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import models.Value;

/**
 *
 * @author radmin
 */
public class PropertyCombineModal extends javax.swing.JDialog {


    /**
     * minimalna liczba miejsc po przecinku dla kosztu
     */
    public static int MinimumFractionDigits = 0;

    /**
     * maksymalna liczba miejsc po przecinku dla kosztu
     */
    public static int MaximumFractionDigits = 0;

    private NumberFormat doubleFormat;

    private Value p;

    /**
     * Creates new form PropertyCombineModalInput
     *
     * @param parent
     * @param modal
     */
    public PropertyCombineModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        formatterInit();
        initComponents();
        getRootPane().setDefaultButton(okButton);
        kosztField.setValue((double) 0);
        p = new Value(null, 0);
    }

    /**
     * inicjuje automatycznie formatowane pole
     */
    private void formatterInit() {
        doubleFormat = NumberFormat.getNumberInstance();
        /*
         Nie wiem dlaczego, ale jak odkomentuję poniższe, to nie działa ;/
         */
        //doubleFormat.setMinimumFractionDigits(PropertyCombineModalInput.MinimumFractionDigits);
        //doubleFormat.setMaximumFractionDigits(PropertyCombineModalInput.MaximumFractionDigits);
        doubleFormat.setParseIntegerOnly(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nazwaLabel = new javax.swing.JLabel();
        nazwaField = new javax.swing.JTextField();
        kosztLabel = new javax.swing.JLabel();
        kosztField = new javax.swing.JFormattedTextField(doubleFormat);
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combine properties");
        setModal(true);
        setName("propertyCombineModal"); // NOI18N
        setResizable(false);

        nazwaLabel.setText("Combined property name");

        kosztLabel.setText("Combine property cost");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nazwaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kosztLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nazwaField)
                    .addComponent(kosztField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nazwaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nazwaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kosztLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kosztField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        exit();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * wyjście z modalu
     */
    private void exit() {
        setVisible(false);
        dispose();
    }

    /**
     * Akcja po kliknięciu przycisku ok
     * @param evt 
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String nazwa = nazwaField.getText();
        Double koszt = (double) 0;

        try {
            if (kosztField.getValue() instanceof Long) {
                Long k = (Long) kosztField.getValue();
                koszt = k.doubleValue();
            } else if (kosztField.getValue() instanceof Double) {
                koszt = (Double) kosztField.getValue();
            } else {
                throw new WrongNumberException("Neiter double nor long given.");
            }
            
            p.setKoszt(koszt);
            p.setNazwa(nazwa);
            exit();
        } catch (WrongNumberException ex) {
            JOptionPane.showMessageDialog(null, "Cost value must be an integer or double.\n" + ex.toString(), "Wrong number format", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    public Value showDialog() {
        setModal(true);
        setVisible(true);
        return p;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField kosztField;
    private javax.swing.JLabel kosztLabel;
    private javax.swing.JTextField nazwaField;
    private javax.swing.JLabel nazwaLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
